version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

orbs:
  node: circleci/node@4.1.0

jobs:

  build:
    executor: node-executor
    steps:
      # Checkout Project from Github
      - checkout

      - run: node --version

      # Setup yarn PackageManager
      - node/install-packages:
          pkg-manager: yarn

      # Not necessary because of auto caching of circleci/node@4.1.0
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "yarn.lock" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      - run:
          name: ⏳ Install
          command: yarn install & npm run package-install

      # Not necessary because of auto caching of circleci/node@4.1.0
      # - save_cache:
      #    key: v1-dependencies-{{ checksum "yarn.lock" }}
      #    paths:
      #      - ./node_modules

      - run:
          name: 🔨 Build Packages
          command: yarn run build

      # https://circleci.com/docs/2.0/configuration-reference/#persist_to_workspace
      - persist_to_workspace:
          root: .
          paths: [ ./* ]

  test:
    executor: node-executor
    steps:
      # https://circleci.com/docs/2.0/configuration-reference/#attach_workspace
      - attach_workspace:
          at: .

      - run: yarn run test

workflows:
  build-and-test:
    jobs:

      # Run Build Job
      - build

      # Run Test Job if Build Job has finished
      - test:
          requires:
            - build
