version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

orbs:
  node: circleci/node@4.0.1

jobs:

  build:
    executor: node-executor
    steps:
      # Checkout Project (only once because the other jobs are waiting for the build job -> there AgileTs is already checked out)
      - checkout

      # Setup yarn PackageManager (only once because the other jobs are waiting for the build job -> there yarn is already setup)
      - node/install-packages:
          pkg-manager: yarn

      # Lint Project
      - run: yarn run lint

      # Build Project
      - run: yarn run build

      - persist_to_workspace:
          root: .
          paths: [ ./* ]

  test:
    working_directory: ~/repo # Where the project gets saved in the docker
    executor: node-executor
    steps:
      # Test Project
      - run: yarn run test

  test-coverage:
    executor: node-executor
    steps:
      # Run Test Coverage
      - run: yarn test:coverage

      # https://circleci.com/docs/2.0/configuration-reference/#store_test_results
      - store_test_results:
          path: ./test-results

      # https://circleci.com/docs/2.0/configuration-reference/#persist_to_workspace
      - persist_to_workspace:
          root: .
          paths: [./*]

workflows:
  build-and-test:
    jobs:

      - build # Run Build Job

      - test: # Run Test Job if Build Job has finished
         requires:
          - build

      - test-coverage: # Run Test-Coverage Job if Build Job has finished
          requires:
            - build
