name: Label Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  labelPR:
    runs-on: ubuntu-latest
    steps:
      - name: 🔰 Label Pull Request
        uses: adamzolyak/monorepo-pr-labeler-action@patching
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}